// Deterministic vulnerability confirmation for the active scanner.
// Given a payload that was sent and the resulting response, each
// analyzer returns a verdict the UI can trust without involving the
// LLM. Regex tables are pragmatic ports of the well-known
// burp-ai-agent ResponseAnalyzer.kt and standard scanner heuristics.

import type { ScannerVulnerabilityClass } from "shared";

export type ResponseAnalyzerVerdict = "confirmed" | "suspicious" | "negative";

export type ResponseAnalyzerResult = {
  verdict: ResponseAnalyzerVerdict;
  evidence: string;
};

export type ResponseAnalyzerInput = {
  className: ScannerVulnerabilityClass;
  payload: string;
  marker: string;
  response: {
    statusCode: number;
    headers: Record<string, string[]>;
    body: string;
  };
};

const SQL_ERROR_PATTERNS: readonly RegExp[] = [
  /SQL syntax.*MySQL/i,
  /Warning.*mysql_/i,
  /valid MySQL result/i,
  /MySqlClient\./i,
  /com\.mysql\.jdbc\.exceptions/i,
  /ORA-\d{5}/,
  /Oracle error/i,
  /Oracle.*Driver/i,
  /Microsoft OLE DB Provider for SQL Server/i,
  /Unclosed quotation mark after the character string/i,
  /SQLServer JDBC Driver/i,
  /PostgreSQL.*ERROR/i,
  /Warning.*pg_/i,
  /valid PostgreSQL result/i,
  /Npgsql\./i,
  /PG::SyntaxError/i,
  /SQLite\/JDBCDriver/i,
  /SQLite\.Exception/i,
  /System\.Data\.SQLite\.SQLiteException/i,
  /Warning.*sqlite_/i,
  /SQLITE_ERROR/i,
  /\[Microsoft\]\[ODBC SQL Server Driver\]/i,
  /SQLSTATE\[\d+\]/i,
  /you have an error in your sql syntax/i,
  /unterminated quoted string at or near/i,
  /quoted string not properly terminated/i,
];

const LFI_CANONICAL_MARKERS: readonly RegExp[] = [
  /root:x:0:0:/,
  /root:\*:0:0:/,
  /daemon:x:1:1:/,
  /\[boot loader\]/i,
  /\[operating systems\]/i,
  /for 16-bit app support/i,
  /; for 16-bit app support/i,
  /\[fonts\]/i,
  /# User Database/,
  /## \s*This file is automatically generated/,
  /# Copyright .* Apple Inc\./,
];

const HTML_ESCAPES = /[&<>"']/;

function headerValues(
  headers: Record<string, string[]>,
  name: string,
): string[] {
  const lower = name.toLowerCase();
  for (const [key, values] of Object.entries(headers)) {
    if (key.toLowerCase() === lower) return values;
  }
  return [];
}

function firstHeaderValue(
  headers: Record<string, string[]>,
  name: string,
): string | undefined {
  const values = headerValues(headers, name);
  return values.length > 0 ? values[0] : undefined;
}

function containsRawReflection(body: string, marker: string): boolean {
  if (marker.length < 4) return false;
  return body.includes(marker);
}

function containsRawReflectionWithDangerousContext(
  body: string,
  payload: string,
): boolean {
  // Only confirmed if the literal payload appears and the payload itself
  // contains an HTML-significant character that was NOT entity-encoded.
  if (!HTML_ESCAPES.test(payload)) return false;
  if (!body.includes(payload)) return false;
  return true;
}

export function analyzeReflectedXss(input: ResponseAnalyzerInput): ResponseAnalyzerResult {
  const { marker, payload, response } = input;
  const body = response.body;

  if (containsRawReflectionWithDangerousContext(body, payload)) {
    const idx = body.indexOf(payload);
    const snippet = body.slice(Math.max(0, idx - 30), idx + payload.length + 30);
    return {
      verdict: "confirmed",
      evidence: `Payload reflected verbatim at offset ${String(idx)}: …${snippet.replace(/\s+/g, " ")}…`,
    };
  }

  if (containsRawReflection(body, marker)) {
    const idx = body.indexOf(marker);
    const snippet = body.slice(Math.max(0, idx - 30), idx + marker.length + 30);
    return {
      verdict: "suspicious",
      evidence: `Marker reflected without dangerous payload context at offset ${String(idx)}: …${snippet.replace(/\s+/g, " ")}…`,
    };
  }

  return { verdict: "negative", evidence: "Payload not reflected in response body." };
}

export function analyzeErrorSqli(input: ResponseAnalyzerInput): ResponseAnalyzerResult {
  const body = input.response.body;
  for (const pattern of SQL_ERROR_PATTERNS) {
    const match = pattern.exec(body);
    if (match !== null) {
      const snippet = body.slice(
        Math.max(0, match.index - 20),
        match.index + match[0].length + 40,
      );
      return {
        verdict: "confirmed",
        evidence: `Database error leak: ${snippet.trim().replace(/\s+/g, " ").slice(0, 200)}`,
      };
    }
  }
  return { verdict: "negative", evidence: "No database error signature in response body." };
}

export function analyzeLfi(input: ResponseAnalyzerInput): ResponseAnalyzerResult {
  const body = input.response.body;
  for (const pattern of LFI_CANONICAL_MARKERS) {
    const match = pattern.exec(body);
    if (match !== null) {
      return {
        verdict: "confirmed",
        evidence: `Canonical file contents returned: "${match[0]}"`,
      };
    }
  }
  return { verdict: "negative", evidence: "No canonical file marker in response body." };
}

// SSTI payloads use arithmetic expansions so the expected result is a
// deterministic numeric value. The payload contains both the template
// expression and the marker, and Drift expects the response body to
// contain the computed number next to (or instead of) the marker.
export function analyzeSsti(input: ResponseAnalyzerInput): ResponseAnalyzerResult {
  const body = input.response.body;
  const expected = extractSstiExpected(input.payload);
  if (expected === undefined) {
    return {
      verdict: "negative",
      evidence: "Payload does not contain a recognisable arithmetic SSTI probe.",
    };
  }
  // Require that the template syntax from the payload is NOT echoed back
  // verbatim (which would mean the server treated it as a literal string)
  // AND the computed number appears in the response.
  if (body.includes(expected.literal)) {
    return {
      verdict: "negative",
      evidence: "Template expression was echoed literally; no evaluation occurred.",
    };
  }
  const numPattern = new RegExp(`\\b${expected.result}\\b`);
  if (numPattern.test(body)) {
    return {
      verdict: "confirmed",
      evidence: `Template expression ${expected.literal} evaluated server-side to ${expected.result}.`,
    };
  }
  return {
    verdict: "negative",
    evidence: `Expected computed value ${expected.result} not found in response.`,
  };
}

function extractSstiExpected(payload: string): { literal: string; result: string } | undefined {
  // Recognise a small set of canonical SSTI probes so analyzers can agree
  // with the generator on the expected result.
  const patterns: Array<{ regex: RegExp; compute: (m: RegExpExecArray) => { literal: string; result: string } }> = [
    {
      regex: /\{\{\s*(\d+)\s*\*\s*(\d+)\s*\}\}/,
      compute: (m) => ({
        literal: m[0],
        result: String(Number(m[1]) * Number(m[2])),
      }),
    },
    {
      regex: /\$\{\s*(\d+)\s*\+\s*(\d+)\s*\}/,
      compute: (m) => ({
        literal: m[0],
        result: String(Number(m[1]) + Number(m[2])),
      }),
    },
    {
      regex: /#\{\s*(\d+)\s*\*\s*(\d+)\s*\}/,
      compute: (m) => ({
        literal: m[0],
        result: String(Number(m[1]) * Number(m[2])),
      }),
    },
    {
      regex: /<%\s*=\s*(\d+)\s*\*\s*(\d+)\s*%>/,
      compute: (m) => ({
        literal: m[0],
        result: String(Number(m[1]) * Number(m[2])),
      }),
    },
  ];
  for (const { regex, compute } of patterns) {
    const match = regex.exec(payload);
    if (match !== null) return compute(match);
  }
  return undefined;
}

export function analyzeOpenRedirect(input: ResponseAnalyzerInput): ResponseAnalyzerResult {
  const { payload, response } = input;
  const status = response.statusCode;
  const locationHeader = firstHeaderValue(response.headers, "location") ?? "";
  const normalized = locationHeader.trim();

  if (status >= 300 && status < 400 && normalized !== "") {
    if (normalized.toLowerCase().startsWith(payload.toLowerCase())) {
      return {
        verdict: "confirmed",
        evidence: `${String(status)} redirect Location header starts with attacker-controlled value: ${normalized.slice(0, 120)}`,
      };
    }
    if (normalized.toLowerCase().includes(payload.toLowerCase())) {
      return {
        verdict: "suspicious",
        evidence: `${String(status)} redirect Location contains attacker input but is not a prefix: ${normalized.slice(0, 120)}`,
      };
    }
  }

  // Some frameworks echo the target in a meta refresh / anchor tag.
  const body = response.body;
  const metaRefresh = /<meta\s+http-equiv=["']refresh["'][^>]*url=([^"'>\s]+)/i.exec(body);
  if (metaRefresh !== null) {
    const target = metaRefresh[1] ?? "";
    if (target !== "" && target.toLowerCase().startsWith(payload.toLowerCase())) {
      return {
        verdict: "confirmed",
        evidence: `Meta refresh redirect target starts with attacker input: ${target.slice(0, 120)}`,
      };
    }
  }

  return { verdict: "negative", evidence: "No redirect surface used the attacker-controlled value as a prefix." };
}

export function analyzeResponse(input: ResponseAnalyzerInput): ResponseAnalyzerResult {
  switch (input.className) {
    case "reflected-xss":
      return analyzeReflectedXss(input);
    case "error-sqli":
      return analyzeErrorSqli(input);
    case "lfi":
      return analyzeLfi(input);
    case "ssti":
      return analyzeSsti(input);
    case "open-redirect":
      return analyzeOpenRedirect(input);
    case "other":
      return {
        verdict: "negative",
        evidence: "`other` class has no deterministic confirmation path in v1.",
      };
  }
}
